server:
  port: 8090

spring:
  application:
    name: best-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: interface_route
          uri: http://localhost:8123
          predicates:
            - Path=/**
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: best-api-admin-consumer
    qosEnable: true
    qosPort: 33333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

