# 公共配置文件
spring:
  application:
    name: best-api-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.01
    port: 6379
  # rabbitmq配置
  rabbitmq:
    host: 127.0.0.01
#    host: 111.229.167.89
    username: root
    password: 123456
    port: 5672
    publisher-confirm-type: correlated #开启发送端确认
    publisher-returns: true #开启发送端消息抵达队列的确认
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnsConfirm
  # session 配置
  session:
    store-type: none
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/best_api
    username: root
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
aliyun:
  oss:
    endpoint: xxxxxx
    urlPrefix: xxxxxx
    accessKeyId: xxxxxx
    accessKeySecret: xxxxx
    bucketName: xxxxx
    fileHost: xxxxx



nero:
  gateway:
    host: http://localhost:8090

dubbo:
  application:
    name: best-api-admin-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
  config-center:
    timeout: 40000

#腾讯短信服务
tencent:
  secretId: xxx
  secretKey: xxx
  sdkAppId: xxx
  signName: xxx
  templateId: xxx
